// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOR8z5iNpZ7eSNgnvmMYBPUJNhoAmfyxk',
    appId: '1:907656246957:web:63c788e239ffe2a23cf824',
    messagingSenderId: '907656246957',
    projectId: 'courtly-65512',
    authDomain: 'courtly-65512.firebaseapp.com',
    storageBucket: 'courtly-65512.appspot.com',
    measurementId: 'G-4S2K3FD6NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvRRM1JTrOo9J0pG7uL4LW02r5i5fxV2Y',
    appId: '1:907656246957:android:569d6bead11f56383cf824',
    messagingSenderId: '907656246957',
    projectId: 'courtly-65512',
    storageBucket: 'courtly-65512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BD9ULo2aqtmgIOZGylqmWB_KT7ix3cI',
    appId: '1:907656246957:ios:61dc80817d06b1d83cf824',
    messagingSenderId: '907656246957',
    projectId: 'courtly-65512',
    storageBucket: 'courtly-65512.appspot.com',
    iosBundleId: 'com.PTLB.courtly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_BD9ULo2aqtmgIOZGylqmWB_KT7ix3cI',
    appId: '1:907656246957:ios:61dc80817d06b1d83cf824',
    messagingSenderId: '907656246957',
    projectId: 'courtly-65512',
    storageBucket: 'courtly-65512.appspot.com',
    iosBundleId: 'com.PTLB.courtly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOR8z5iNpZ7eSNgnvmMYBPUJNhoAmfyxk',
    appId: '1:907656246957:web:d1e00d6f8ccb1f153cf824',
    messagingSenderId: '907656246957',
    projectId: 'courtly-65512',
    authDomain: 'courtly-65512.firebaseapp.com',
    storageBucket: 'courtly-65512.appspot.com',
    measurementId: 'G-E5MD2D27KG',
  );
}
